---
title: "BST430 - Introduction to Statistical Computing"
description: "University of Rochester, Fall 2021"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Administrivia

MW 11:00-12:40, SRB 1402
<br>
**Instructor**: Andrew McDavid
<br>
**Website**: https://urmc-bst.github.io/bst430-fall2021-site/
<br>
[**Syllabus**](static/Syllabus_DRAFT.pdf)

# Content

0. [Introduction](lecture/l00-intro.html)
    * [Survey](https://forms.gle/yJ8NVHbsJmanSywz9)
1. [Meet the toolkit](lecture/l01-meet-toolkit.html)
    * Invites to rstudio cloud and github class room are on [blackboard](https://learn.rochester.edu)
    * Req readings: r4ds 3.1-3.5, 4. Optional: https://happygitwithr.com/
<!-- * Resources: [rstudio](https://www.rstudio.com/products/rstudio/download/#download) https://cran.r-project.org/ -->
2. [ggplot(i)](lecture/l02-ggplot2-i.html)
    * CandyWeight for real.
    * Lab 1 [instructions](hw_lab_instruction/lab01-hello-r.html) and repo (accept GH classroom invite). Due 5pm Sept 3.
3.  [dplyr(i)](lecture/l03-transform-dplyr-i.html)
    * Continue working on lab 1
4.  [Data types in R](lecture/l04-data-types.html). Finish dplyr(i) lecture.
    * HW 1 assigned.  [instructions](hw_lab_instruction/hw-01-airbnb/hw-01-airbnb.html) and repo (accept GH classroom invite).  Due 5pm EDT, Sept 13.
5.  [Reshaping and combining data frames](lecture/l05a-reshape-merge.html). Finish data types lecture.
    *  [Lab 2](hw_lab_instruction/lab02-merge-conflict/lab02-merge-conflict.html). You will need to accept an invitation to join the URMC-BST organization to get access to your repositories to complete these.  Most labs will be completed **in groups** going forward -- if you cannot attend class in person for whatever reason, let me know and I'll set up zoom so you can participate **synchronously and remotely.**
6.  Finish L5a.
    *  [Lab 3](hw_lab_instruction/lab03-laquinta-uno/lab03-laquinta-uno.html).  To be completed in same group as lab 2.
7.  [dplyr(ii)](lecture/l05b-advanced-dplyr.html), [styleguide](lecture/l06-style.html)
    *  [Lab 4](hw_lab_instruction/lab04-laquinta-dos/lab04-laquinta-dos.html).  New groups!
8.  [Factors and dates](lecture/l07-factors-dates.html)
    *  [HW 2](hw_lab_instruction/hw02-accidents/hw02-accidents.html) assigned.


